template_links:
  emails:
    - hello
  webhooks:
    - hello
    - bye

webhooks:
  hello:
    - http://gin-server:8080/hello
    - http://gin-server:8080/hello2
  bye:
    - http://gin-server:8080/bye
