name: learn-github-actions
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./publisher/...
      - name: Test
        run: go test -v ./publisher/...

      - name: Build
        run: go build -v ./subscriber/...
      - name: Test
        run: go test -v ./subscriber/...
