name: learn-github-actions
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build
        run: cd ./publisher && go build -v ./...
      - name: Test
        run: cd ./publisher && go test -v ./...

      - name: Build
        run: cd ./subscriber && go build -v ./...
      - name: Test
        run: cd ./subscriber && go test -v ./...
